import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { Activity, Cable, CheckCircle2, KeyRound, RefreshCw, ShieldCheck, Unplug } from "lucide-react";
import React, { useState } from "react";
import { toast } from "sonner";

const apiControlCopy = {
  ar: {
    ownerOnly: "خاص بالمالك", title: "مركز تحكم DevForge API", intro: "سجل العقود والعناوين النشطة الآمنة للمنصة. يعرض المركز النطاق والحالة التشغيلية المتاحة فقط؛ لا يعرض مفاتيحًا أو عناوين داخلية أو إعدادات مزودين.", health: "إشارة الصحة", loading: "يجري فحص الإشارة…", available: "متاح", unavailable: "غير متاح حاليًا", separation: "مراجعة فصل الاتصال", separationCopy: "هذا الخيار يسجل فقط رغبة المالك في مراجعة عزل عقد API أو انتقاله مستقبلًا. لا يفصل أي خدمة، ولا ينقل الاستضافة، ولا ينشئ بيانات اعتماد أو اتصالًا خارجيًا.", record: "سجل مراجعة فصل API", recording: "يجري تسجيل المراجعة…", recorded: "سُجلت مراجعة فصل API. لم يتغير أي اتصال أو استضافة.", refresh: "تحديث إشارة الصحة", contracts: "عقود API النشطة", shows: "ما يظهر هنا", showsCopy: "العناوين العامة، العقود المحمية، وإشارة الصحة فقط. حالة «عند الطلب» تعني أن الواجهة لا تعمل في الخلفية ولا تشير إلى اتصال خارجي نشط.", hides: "ما لا يظهر هنا", hidesCopy: "لا مفاتيح API، ولا رموز جلسات، ولا عناوين خوادم داخلية، ولا سجلات زوار، ولا بيانات مقدمي الخدمة أو الحسابات الخارجية.", contractsList: [
      ["بوابة DevForge API", "/api/trpc", "عقد النقل الموحد", "عنوان نشط"], ["إشارة الصحة", "/api/trpc/system.health", "قراءة عامة محدودة", "فحص متاح"], ["موجز المجتمع", "/api/trpc/communityHub.publicFeed", "منشورات معتمدة فقط", "عند الطلب"], ["موجز وسائط الزوار", "/api/trpc/visitorSubmissions.approvedFeed", "وسائط معتمدة فقط", "عند الطلب"], ["مساحات المالك", "/api/trpc/{workspace,sourceFiles,aiWorkspace,globalResearch}", "مصادقة المالك مطلوبة", "محمي"], ["المراجعة والتكاملات", "/api/trpc/{integrationCenter,developerCenter,githubWorkspace}", "مصادقة ومراجعة صريحة", "محمي"],
    ],
  },
  en: {
    ownerOnly: "Owner only", title: "DevForge API Control Center", intro: "A record of safe active contracts and addresses for the platform. The center shows only available scope and operational status; it never shows keys, internal addresses, or provider settings.", health: "Health signal", loading: "Checking the signal…", available: "Available", unavailable: "Currently unavailable", separation: "Connection-separation review", separationCopy: "This option records only the owner’s request to review future API-contract isolation or migration. It does not disconnect a service, move hosting, create credentials, or establish an external connection.", record: "Record API-separation review", recording: "Recording review…", recorded: "The API-separation review was recorded. No connection or hosting changed.", refresh: "Refresh health signal", contracts: "Active API contracts", shows: "What appears here", showsCopy: "Public addresses, protected contracts, and the health signal only. “On demand” means the interface does not run in the background or indicate an active external connection.", hides: "What does not appear here", hidesCopy: "No API keys, session tokens, internal server addresses, visitor records, or external-provider and account data.", contractsList: [
      ["DevForge API gateway", "/api/trpc", "Unified transport contract", "Active address"], ["Health signal", "/api/trpc/system.health", "Limited public read", "Probe available"], ["Community feed", "/api/trpc/communityHub.publicFeed", "Approved posts only", "On demand"], ["Visitor media feed", "/api/trpc/visitorSubmissions.approvedFeed", "Approved media only", "On demand"], ["Owner workspaces", "/api/trpc/{workspace,sourceFiles,aiWorkspace,globalResearch}", "Owner authentication required", "Protected"], ["Review and integrations", "/api/trpc/{integrationCenter,developerCenter,githubWorkspace}", "Authentication and explicit review", "Protected"],
    ],
  },
} as const;

export default function ApiControlCenter() {
  const { direction, language } = useLanguage();
  const copy = apiControlCopy[language === "en" ? "en" : "ar"];
  const [timestamp, setTimestamp] = useState(() => Date.now());
  const health = trpc.system.health.useQuery({ timestamp });
  const requestSeparation = trpc.integrationCenter.request.useMutation({ onSuccess: () => toast.success(copy.recorded), onError: issue => toast.error(issue.message) });
  const origin = typeof window === "undefined" ? "" : window.location.origin;
  const healthLabel = health.isLoading ? copy.loading : health.data?.ok ? copy.available : copy.unavailable;
  return <DashboardLayout><section dir={direction} className="mx-auto max-w-6xl space-y-5">
    <header className="rounded-[2rem] border border-cyan-300/20 bg-gradient-to-l from-cyan-300/10 via-slate-950 to-indigo-400/10 p-6 sm:p-8"><Badge className="border border-cyan-300/25 bg-cyan-300/10 text-cyan-100"><Cable className="ml-1 h-3.5 w-3.5" />{copy.ownerOnly}</Badge><div className="mt-5 flex flex-wrap items-start justify-between gap-5"><div><h1 className="text-2xl font-bold text-white sm:text-3xl">{copy.title}</h1><p className="mt-2 max-w-3xl leading-8 text-slate-300">{copy.intro}</p></div><div className="rounded-2xl border border-cyan-300/20 bg-black/25 px-4 py-3 text-sm text-cyan-100"><Activity className="ml-2 inline h-4 w-4" />{copy.health}: <strong>{healthLabel}</strong></div></div></header>
    <Card className="border-amber-300/20 bg-amber-300/[0.045] text-amber-50"><CardHeader><CardTitle className="flex items-center gap-2 text-amber-100"><Unplug className="h-5 w-5" />{copy.separation}</CardTitle><CardDescription className="leading-7 text-amber-100/75">{copy.separationCopy}</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-3"><Button onClick={() => requestSeparation.mutate({ providerKey: "devforge-api-boundary" })} disabled={requestSeparation.isPending} className="bg-amber-300 text-slate-950 hover:bg-amber-200"><ShieldCheck className="ml-2 h-4 w-4" />{requestSeparation.isPending ? copy.recording : copy.record}</Button><Button variant="outline" onClick={() => { setTimestamp(Date.now()); health.refetch(); }} className="border-amber-300/30 text-amber-100 hover:bg-amber-300/10 hover:text-amber-50"><RefreshCw className="ml-2 h-4 w-4" />{copy.refresh}</Button></CardContent></Card>
    <section aria-label={copy.contracts} className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{copy.contractsList.map(([name, path, scope, activity]) => <Card key={path} className="flex min-w-0 flex-col border-white/10 bg-slate-950/60 text-white"><CardHeader className="pb-3"><div className="flex items-start justify-between gap-3"><CardTitle className="text-lg">{name}</CardTitle><Badge variant="outline" className="border-cyan-300/25 text-cyan-100">{activity}</Badge></div><CardDescription className="mt-3 text-slate-400">{scope}</CardDescription></CardHeader><CardContent className="mt-auto"><code dir="ltr" className="block overflow-x-auto rounded-xl border border-white/10 bg-black/30 px-3 py-3 text-left text-xs text-cyan-100">{origin}{path}</code></CardContent></Card>)}</section>
    <section className="grid gap-4 md:grid-cols-2"><Card className="border-white/10 bg-slate-950/60 text-white"><CardHeader><CardTitle className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-emerald-300" />{copy.shows}</CardTitle></CardHeader><CardContent className="text-sm leading-7 text-slate-400">{copy.showsCopy}</CardContent></Card><Card className="border-white/10 bg-slate-950/60 text-white"><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound className="h-5 w-5 text-rose-200" />{copy.hides}</CardTitle></CardHeader><CardContent className="text-sm leading-7 text-slate-400">{copy.hidesCopy}</CardContent></Card></section>
  </section></DashboardLayout>;
}
