import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useLanguage } from "@/contexts/LanguageContext";
import { ArrowLeft, ExternalLink, KeyRound, ShieldCheck } from "lucide-react";
import React from "react";
import { Link } from "wouter";

const endpoint = typeof window === "undefined" ? "/api/trpc" : `${window.location.origin}/api/trpc`;

export default function ApiReferencePage() {
  const { direction } = useLanguage();
  return <main dir={direction} className="dev-shell min-h-screen px-4 py-8 text-right sm:px-6 sm:py-14"><section className="mx-auto max-w-4xl"><Link href="/"><Button variant="outline" className="border-white/15 bg-white/[0.03] text-white hover:bg-white/[0.08] hover:text-white"><ArrowLeft className="ml-2 h-4 w-4" />العودة للرئيسية</Button></Link><article className="mt-6 rounded-[2rem] border border-cyan-300/15 bg-slate-950/70 p-6 shadow-2xl shadow-cyan-950/20 sm:p-10"><Badge className="border border-cyan-300/20 bg-cyan-300/10 text-cyan-100">DEVFORGE API</Badge><h1 className="mt-5 text-3xl font-bold text-white sm:text-4xl">مرجع الوصول إلى DevForge API</h1><p className="mt-4 max-w-3xl leading-8 text-slate-300">هذا هو عقد API الخاص بـ DevForge على عنوانه النشط. استخدمه من تطبيق موثوق ومصادق عليه فقط. طبقة الاستضافة الحالية لا تغير صلاحيات العقد: الوصول إلى المشاريع والأكواد والمراجعات والمراسلات يخضع لتسجيل الدخول وصلاحيات المستخدم، ولا تعرض DevForge مفاتيح أو رموز وصول في هذه الصفحة.</p><code dir="ltr" className="mt-7 block max-w-full overflow-x-auto rounded-2xl border border-cyan-300/15 bg-black/30 px-4 py-4 text-left text-sm text-cyan-100">{endpoint}</code><div className="mt-7 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/8 bg-white/[0.03] p-4"><ShieldCheck className="h-5 w-5 text-cyan-300" /><h2 className="mt-4 font-bold text-white">وصول محمي</h2><p className="mt-2 text-sm leading-7 text-slate-400">تعمل النقاط العامة المحدودة دون كشف بيانات خاصة، أما البيانات الشخصية وبيانات العمل فتتطلب المصادقة.</p></div><div className="rounded-2xl border border-white/8 bg-white/[0.03] p-4"><KeyRound className="h-5 w-5 text-amber-200" /><h2 className="mt-4 font-bold text-white">لا مفاتيح في المتصفح</h2><p className="mt-2 text-sm leading-7 text-slate-400">لا تضع مفتاح API أو رمز دخول في رابط أو شفرة واجهة عامة. تبقى بيانات الاعتماد في الخادم أو مدير الأسرار.</p></div></div><a href={endpoint} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-cyan-200 hover:text-cyan-100">فتح رابط API <ExternalLink className="h-4 w-4" /></a></article></section></main>;
}
