import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { reliabilityServiceCatalog } from "@shared/reliabilityServiceCatalog";
import { Activity, ExternalLink, HeartPulse, RefreshCw, ShieldCheck, TerminalSquare } from "lucide-react";
import React, { useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

export default function ContinuityCenter() {
  const { direction } = useLanguage();
  const [, setLocation] = useLocation();
  const [probeTimestamp, setProbeTimestamp] = useState(() => Date.now());
  const utils = trpc.useUtils();
  const health = trpc.system.health.useQuery({ timestamp: probeTimestamp }, { retry: 0 });
  const { data: preferences = [] } = trpc.integrationCenter.list.useQuery();
  const request = trpc.integrationCenter.request.useMutation({
    onSuccess: () => { utils.integrationCenter.list.invalidate(); toast.success("سُجل طلب مراجعة خدمة الاستمرارية. لا توجد مراقبة أو مشاركة بيانات مفعلة بعد."); },
    onError: issue => toast.error(issue.message),
  });
  const requested = useMemo(() => new Set(preferences.map(item => item.providerKey)), [preferences]);
  const status = health.isLoading ? "جارٍ الفحص" : health.data?.ok ? "استجابة محلية متاحة" : "لم تصل الاستجابة";
  const statusTone = health.isLoading ? "text-amber-100 border-amber-300/20 bg-amber-300/5" : health.data?.ok ? "text-emerald-100 border-emerald-300/20 bg-emerald-300/5" : "text-rose-100 border-rose-300/20 bg-rose-300/5";

  return <DashboardLayout><main dir={direction} className="mx-auto max-w-6xl space-y-5 sm:space-y-6">
    <header className="relative overflow-hidden rounded-[2rem] border border-cyan-300/15 bg-gradient-to-l from-cyan-400/15 via-slate-950 to-emerald-400/10 p-6 sm:p-8"><div className="absolute -left-10 -top-10 h-40 w-40 rounded-full bg-cyan-300/10 blur-3xl" /><Badge className="relative border border-cyan-300/20 bg-cyan-300/10 text-cyan-100"><ShieldCheck className="ml-1 h-3.5 w-3.5" />خاص بالمالك · استجابة ومراجعة</Badge><div className="relative mt-5 flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-cyan-300 text-slate-950"><HeartPulse className="h-6 w-6" /></div><div><h1 className="text-2xl font-bold text-white sm:text-3xl">مركز الاستمرارية</h1><p className="mt-2 max-w-3xl leading-8 text-slate-300">تشغيل DevForge المنشور مستقل عن جلسة المحادثة. تعرض هذه الصفحة إشارة استجابة محدودة من الخادم وخيارات مراقبة خارجية موثقة، لكن لا تعيد تشغيل خدمات ولا تغيّر كودًا أو بنية أو حسابات تلقائيًا.</p></div></div></header>
    <section className={`rounded-3xl border p-5 sm:p-6 ${statusTone}`}><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-start gap-3"><Activity className="mt-0.5 h-5 w-5 shrink-0" /><div><h2 className="font-bold">إشارة الاستجابة الحالية</h2><p className="mt-1 text-sm leading-6 opacity-80">{status}. هذا الفحص يطلب حالة خادم DevForge فقط، ولا يختبر حسابات المالك أو بيانات الزوار أو أي خدمة خارجية.</p></div></div><Button variant="outline" onClick={() => { setProbeTimestamp(Date.now()); void health.refetch(); }} disabled={health.isFetching} className="border-current bg-transparent text-current hover:bg-white/10 hover:text-current"><RefreshCw className={`ml-1 h-4 w-4 ${health.isFetching ? "animate-spin" : ""}`} />فحص جديد</Button></div>{health.isError ? <p className="mt-4 rounded-xl border border-rose-300/20 bg-rose-300/5 p-3 text-sm leading-7 text-rose-100">تعذر الحصول على إشارة الاستجابة الآن. راجع صفحة النشر أو خدمات المراقبة التي تعتمدها بنفسك؛ لا يجري DevForge إعادة تشغيل تلقائية.</p> : null}</section>
    <section className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_300px]"><div className="rounded-3xl border border-white/8 bg-slate-950/55 p-5 sm:p-6"><h2 className="font-bold text-white">مسار التعافي المنظم</h2><ol className="mt-4 space-y-3 text-sm leading-7 text-slate-300"><li><strong className="text-cyan-100">1. افحص الاستجابة:</strong> حدّث الفحص المحلي أو تحقق من رابط الإنتاج.</li><li><strong className="text-cyan-100">2. راجع الدليل:</strong> يوضح كل مزود نطاق بياناته وطريقة تفعيله من حساب المالك.</li><li><strong className="text-cyan-100">3. شخّص التجربة:</strong> افتح محطة JavaScript لتشخيص خطأ محلي والحصول على اقتراح قابل للمراجعة.</li><li><strong className="text-cyan-100">4. نفّذ يدويًا:</strong> أي نشر أو إعداد مراقبة أو تعديل كود يتطلب قرارًا صريحًا من المالك.</li></ol></div><aside className="rounded-3xl border border-amber-300/15 bg-amber-300/[0.04] p-5"><TerminalSquare className="h-5 w-5 text-amber-300" /><h2 className="mt-3 font-bold text-amber-100">تشخيص JavaScript</h2><p className="mt-2 text-sm leading-7 text-amber-100/70">التشخيص يولّد اقتراحًا محليًا فقط. لا يطبق الإصلاح ولا يفتح الشبكة أو الملفات أو حسابات الخدمات.</p><Button onClick={() => setLocation("/javascript-lab")} variant="outline" className="mt-4 w-full border-amber-300/30 text-amber-100 hover:bg-amber-300/10 hover:text-amber-50">فتح التشخيص المحلي</Button></aside></section>
    <section aria-label="خدمات الاستمرارية المقترحة" className="rounded-3xl border border-white/8 bg-white/[0.02] p-5 sm:p-6"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-emerald-300" /><div><h2 className="font-bold text-white">خدمات استمرارية موثقة</h2><p className="mt-1 text-sm leading-6 text-slate-500">يعرض هذا الدليل مزودين مناسبين لأغراض مختلفة، لا ضمانات إتاحة أو اتصالًا قائمًا. راجع الشروط والتسعير والخصوصية لدى كل مزود قبل التفعيل.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{reliabilityServiceCatalog.map(service => <article key={service.providerKey} className="flex min-w-0 flex-col rounded-2xl border border-white/8 bg-slate-950/50 p-4"><Badge variant="outline" className="w-fit border-emerald-300/20 text-emerald-100">{service.focus}</Badge><h3 className="mt-3 font-bold text-white">{service.name}</h3><p className="mt-2 min-h-20 text-sm leading-6 text-slate-400">{service.description}</p><p className="mt-3 rounded-xl border border-amber-300/10 bg-amber-300/[0.03] p-3 text-xs leading-6 text-amber-100/75">{service.activationBoundary}</p><a href={service.documentationUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1.5 text-xs font-bold text-cyan-200 hover:text-cyan-100">التوثيق الرسمي<ExternalLink className="h-3.5 w-3.5" /></a><Button disabled={request.isPending || requested.has(service.providerKey)} onClick={() => request.mutate({ providerKey: service.providerKey })} className="mt-4 w-full">{requested.has(service.providerKey) ? "طلب المراجعة مسجل" : "طلب مراجعة الربط"}</Button></article>)}</div></section>
  </main></DashboardLayout>;
}
