import React from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { Badge } from "@/components/ui/badge";
import IosInstallGuide from "@/components/IosInstallGuide";
import { LanguageSelector, useLanguage } from "@/contexts/LanguageContext";
import { ArrowLeft, ArrowUpLeft, Blocks, Bot, CheckCircle2, ChevronLeft, CloudCog, Code2, GitBranch, GitPullRequest, Layers3, MessageCircleMore, Play, Rocket, ScanSearch, ShieldCheck, Sparkles, Terminal, UserRound, UsersRound } from "lucide-react";
import { Link } from "wouter";

export default function Home() {
  const { direction, t } = useLanguage();
  const { user, loading } = useAuth();
  const operations = [
    { icon: GitPullRequest, title: t("fasterReview"), copy: t("fasterReviewCopy"), tone: "text-cyan-300", path: "/plans", action: "فتح مسار المراجعة" },
    { icon: Rocket, title: t("clearerReleases"), copy: t("clearerReleasesCopy"), tone: "text-violet-300", path: "/website-studio", action: "بدء بناء منظم" },
    { icon: ShieldCheck, title: t("measurableQuality"), copy: t("measurableQualityCopy"), tone: "text-emerald-300", path: "/developer-center", action: "فتح مركز الجودة" },
  ];
  const workflow = [{ n: "01", title: t("plan"), copy: t("planCopy") }, { n: "02", title: t("build"), copy: t("buildCopy") }, { n: "03", title: t("review"), copy: t("reviewCopy") }, { n: "04", title: t("launch"), copy: t("launchCopy") }];
  return (
    <main dir={direction} className="dev-shell min-h-screen overflow-hidden text-right">
      <div className="pointer-events-none fixed inset-0 overflow-hidden"><div className="dev-orb left-[-12rem] top-24 h-[30rem] w-[30rem] bg-cyan-400/15" /><div className="dev-orb right-[-10rem] top-[32rem] h-[32rem] w-[32rem] bg-violet-500/12" /></div>
      <nav className="container relative z-10 flex h-20 items-center justify-between border-b border-white/8">
        <Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-300 text-slate-950 shadow-lg shadow-cyan-400/15"><Blocks className="h-5 w-5" /></span><span className="font-mono text-xl font-bold tracking-tight text-white">Dev<span className="text-cyan-300">Forge</span></span></Link>
        <div className="hidden items-center gap-7 text-sm text-slate-400 md:flex"><a href="#capabilities" className="hover:text-white">{t("capabilities")}</a><a href="#workflow" className="hover:text-white">{t("workflow")}</a><a href="#control" className="hover:text-white">{t("control")}</a></div>
        <div className="flex items-center gap-2"><LanguageSelector compact />{!loading && (user ? <Link href="/visitor/messages"><Button variant="outline" className="h-10 rounded-xl border-cyan-300/20 bg-cyan-300/8 px-3 text-cyan-100 hover:bg-cyan-300/15 hover:text-cyan-50"><MessageCircleMore className="h-4 w-4 sm:ml-2" /><span className="hidden sm:inline">مراسلاتي</span></Button></Link> : <Button onClick={() => startLogin()} variant="outline" className="h-10 rounded-xl border-white/15 bg-white/3 px-3 text-white hover:bg-white/8 hover:text-white"><UserRound className="h-4 w-4 sm:ml-2" /><span className="hidden sm:inline">دخول الزوار</span></Button>)}<Link href="/community"><Button aria-label="المجتمعات" variant="outline" className="h-10 rounded-xl border-violet-300/20 bg-violet-300/8 px-3 text-violet-100 hover:bg-violet-300/15 hover:text-violet-50"><UsersRound className="h-4 w-4 sm:ml-2" /><span className="hidden sm:inline">المجتمعات</span></Button></Link><Link href="/share"><Button variant="outline" className="hidden h-10 rounded-xl border-white/15 bg-white/3 px-4 text-white hover:bg-white/8 hover:text-white sm:inline-flex">شارك</Button></Link><Link href="/plans"><Button className="h-10 rounded-xl bg-white px-4 font-bold text-slate-950 hover:bg-cyan-100">{t("startJourney")} <ArrowLeft className="mr-2 h-4 w-4" /></Button></Link></div>
      </nav>

      <div className="container relative z-10"><IosInstallGuide /></div>

      <section className="container relative z-10 pt-5"><div className="flex flex-wrap items-center gap-2 border-y border-white/7 py-3"><span className="command-label">devforge / control-plane</span><Link href="/plans" className="signal-chip hover:border-cyan-300/30 hover:text-white"><span className="signal-dot" />مراجعات منظمة</Link><Link href="/share" className="signal-chip hover:border-violet-300/30 hover:text-white"><span className="h-1.5 w-1.5 rounded-full bg-violet-300" />مشاركة خاضعة للإشراف</Link><Link href="/community" className="signal-chip hover:border-violet-300/30 hover:text-white"><span className="h-1.5 w-1.5 rounded-full bg-violet-300" />مجتمعات بموافقة</Link><Link href="/visitor/messages" className="signal-chip hover:border-emerald-300/30 hover:text-white"><span className="h-1.5 w-1.5 rounded-full bg-emerald-300" />خصوصية افتراضية</Link></div></section>
      <section className="container relative z-10 grid gap-14 py-16 lg:grid-cols-[1fr_0.95fr] lg:items-center lg:py-24">
        <div><Badge className="border border-cyan-300/20 bg-cyan-300/8 px-3 py-1 text-cyan-200 hover:bg-cyan-300/8"><Sparkles className="ml-1 h-3.5 w-3.5" /> {t("engineeringPlatform")}</Badge><h1 className="mt-7 max-w-3xl text-5xl font-black leading-[1.14] tracking-tight text-white sm:text-6xl">{t("heroStart")} <span className="text-cyan-300">{t("heroAccent")}</span><br />{t("heroEnd")}</h1><p className="mt-7 max-w-xl text-lg leading-9 text-slate-400">{t("heroCopy")}</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/plans"><Button size="lg" className="h-13 rounded-xl bg-cyan-300 px-6 font-bold text-slate-950 hover:bg-cyan-200">{t("startJourney")} <ArrowLeft className="mr-2 h-4 w-4" /></Button></Link><Link href="/website-studio"><Button size="lg" variant="outline" className="h-13 rounded-xl border-white/15 bg-white/3 px-6 text-white hover:bg-white/8 hover:text-white"><Play className="ml-2 h-4 w-4 fill-current" /> {t("websiteBuilder")}</Button></Link></div><div className="mt-12 flex flex-wrap gap-x-8 gap-y-4 text-sm text-slate-400">{[t("projectsReleases"), t("reviewsChecks"), t("liveOperations")].map(item => <span key={item} className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-cyan-300" />{item}</span>)}</div></div>

        <section className="relative mx-auto w-full max-w-[610px] rounded-[2rem] border border-white/10 bg-slate-950/70 p-3 shadow-2xl shadow-black/35 backdrop-blur-xl"><div className="rounded-[1.5rem] border border-white/8 bg-[#0b1222] p-5"><div className="mb-7 flex items-center justify-between"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-rose-400" /><span className="h-2.5 w-2.5 rounded-full bg-amber-300" /><span className="h-2.5 w-2.5 rounded-full bg-emerald-300" /></div><span className="font-mono text-xs text-slate-500">release-control / overview</span></div><div className="grid grid-cols-[0.72fr_1.28fr] gap-4"><aside className="rounded-2xl bg-white/[0.035] p-3"><p className="mb-4 text-[10px] font-bold tracking-[0.16em] text-slate-500">{t("workspace")}</p>{[t("overview"), t("projects"), t("pullRequests"), t("releases")].map((item, index) => <div key={item} className={`mb-2 flex items-center gap-2 rounded-lg px-2 py-2 text-xs ${index === 0 ? "bg-cyan-300/12 text-cyan-200" : "text-slate-500"}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{item}</div>)}</aside><div className="space-y-4"><div className="rounded-2xl bg-gradient-to-l from-cyan-300/14 to-violet-400/10 p-4"><div className="flex items-start justify-between"><div><p className="text-xs text-slate-400">{t("deliveryHealth")}</p><p className="mt-1 text-2xl font-bold text-white">{t("onTrack")}</p></div><span className="rounded-lg bg-emerald-400/15 px-2 py-1 text-[10px] font-bold text-emerald-300">{t("stability")}</span></div><div className="mt-5 flex h-12 items-end gap-1.5">{[35, 46, 38, 62, 55, 72, 64, 88, 76, 94, 82, 100].map((height, index) => <span key={index} className="flex-1 rounded-t bg-cyan-300/80" style={{ height: `${height}%`, opacity: index === 11 ? 1 : 0.35 + index / 24 }} />)}</div></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/[0.035] p-3"><GitPullRequest className="h-4 w-4 text-violet-300" /><p className="mt-5 text-xl font-bold text-white">18</p><p className="text-[11px] text-slate-500">{t("reviewQueue")}</p></div><div className="rounded-2xl bg-white/[0.035] p-3"><Rocket className="h-4 w-4 text-cyan-300" /><p className="mt-5 text-xl font-bold text-white">v2.8.0</p><p className="text-[11px] text-slate-500">{t("releaseReady")}</p></div></div><div className="rounded-2xl border border-emerald-400/12 bg-emerald-400/5 p-3"><div className="flex items-center gap-2 text-xs font-bold text-emerald-200"><CheckCircle2 className="h-4 w-4" /> {t("checksComplete")}</div><p className="mt-1 text-[11px] text-slate-400">commit 8a3f9e · production candidate</p></div></div></div></div></section>
      </section>

      <section id="capabilities" className="container relative z-10 py-10 lg:py-20"><div className="mb-10 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="font-mono text-xs font-bold tracking-[0.2em] text-cyan-300">{t("builtForFlow")}</p><h2 className="mt-3 text-3xl font-bold text-white">{t("everyDecision")}</h2></div><p className="max-w-md leading-7 text-slate-500">{t("contextCopy")}</p></div><div className="grid gap-4 md:grid-cols-3">{operations.map(operation => <Link href={operation.path} key={operation.title} className="group rounded-3xl border border-white/8 bg-white/[0.03] p-7 transition duration-200 hover:-translate-y-1 hover:border-cyan-300/20 hover:bg-white/[0.05]"><operation.icon className={`h-6 w-6 ${operation.tone}`} /><h3 className="mt-10 text-xl font-bold text-white">{operation.title}</h3><p className="mt-3 leading-7 text-slate-500">{operation.copy}</p><span className="mt-8 inline-flex items-center text-sm font-bold text-slate-300 transition group-hover:text-cyan-200">{operation.action} <ArrowUpLeft className="mr-1 h-4 w-4" /></span></Link>)}</div></section>

      <section id="workflow" className="container relative z-10 py-20"><div className="grid gap-8 rounded-[2rem] border border-white/8 bg-gradient-to-l from-white/[0.05] to-transparent p-7 md:p-10 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="font-mono text-xs font-bold tracking-[0.2em] text-violet-300">{t("deliveryLoop")}</p><h2 className="mt-4 text-3xl font-bold leading-tight text-white">{t("firstTask")}<br />{t("auditableLaunch")}</h2><p className="mt-5 leading-8 text-slate-400">{t("workflowCopy")}</p></div><div className="grid gap-3 sm:grid-cols-2">{workflow.map(step => <div key={step.n} className="rounded-2xl border border-white/8 bg-slate-950/45 p-5"><span className="font-mono text-xs text-cyan-300">{step.n}</span><h3 className="mt-5 text-lg font-bold text-white">{step.title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{step.copy}</p></div>)}</div></div></section>

      <section id="control" className="container relative z-10 py-14 pb-24"><div className="rounded-[2rem] border border-cyan-300/15 bg-cyan-300/[0.045] p-8 text-center md:p-14"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-cyan-300 text-slate-950"><Bot className="h-6 w-6" /></div><h2 className="mx-auto mt-6 max-w-2xl text-3xl font-bold leading-tight text-white">{t("controlTitle")}</h2><p className="mx-auto mt-4 max-w-xl leading-7 text-slate-400">{t("controlCopy")}</p><Link href="/plans"><Button className="mt-8 h-12 rounded-xl bg-cyan-300 px-6 font-bold text-slate-950 hover:bg-cyan-200">{t("choosePlan")} <ChevronLeft className="mr-2 h-4 w-4" /></Button></Link></div></section>
      <footer className="container relative z-10 flex flex-col gap-4 border-t border-white/8 py-8 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span className="font-mono">DEVFORGE / ENGINEERING PLATFORM</span><span>{t("footer")}</span></footer>
    </main>
  );
}
