import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Store, XCircle } from "lucide-react";
import React from "react";
import { toast } from "sonner";

export default function MarketplaceReviewCenter() {
  const { direction } = useLanguage(); const utils = trpc.useUtils(); const queue = trpc.marketplace.reviewQueue.useQuery();
  const moderate = trpc.marketplace.moderate.useMutation({ onSuccess: async () => { await Promise.all([utils.marketplace.reviewQueue.invalidate(), utils.marketplace.publicStores.invalidate()]); toast.success("تم حفظ قرار المراجعة."); }, onError: issue => toast.error(issue.message) });
  return <DashboardLayout><section dir={direction} className="space-y-5"><header className="rounded-[2rem] border border-violet-300/15 bg-gradient-to-l from-violet-400/12 via-slate-950 to-cyan-400/10 p-6 sm:p-8"><Badge className="border border-violet-300/20 bg-violet-300/10 text-violet-100">مراجعة المالك</Badge><div className="mt-4 flex gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-violet-300 text-slate-950"><Store className="h-6 w-6" /></div><div><h1 className="text-2xl font-bold text-white sm:text-3xl">مراجعة طلبات المتاجر</h1><p className="mt-2 max-w-3xl leading-8 text-slate-300">اعتمد متجرًا حقيقيًا أو ارفضه قبل ظهوره للعامة. لا تنشئ هذه الإجراءات منتجات أو دفعات أو حسابات مالية.</p></div></div></header><section className="rounded-3xl border border-white/8 bg-slate-950/60 p-5"><div className="flex items-center justify-between"><h2 className="font-bold text-white">طلبات معلقة</h2><Badge variant="outline" className="border-white/10 text-slate-400">{queue.data?.length ?? 0}</Badge></div><div className="mt-5 space-y-3">{queue.isLoading ? <p className="text-sm text-slate-500">يجري تحميل الطلبات…</p> : queue.data?.length ? queue.data.map(store => <article key={store.id} className="rounded-2xl border border-white/8 bg-white/[0.025] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold text-white">{store.name}</h3><p className="mt-1 font-mono text-xs text-slate-600">/{store.slug} · {store.category}</p></div><Badge className="border border-amber-300/15 bg-amber-300/10 text-amber-100">قيد المراجعة</Badge></div><p className="mt-3 text-sm leading-7 text-slate-400">{store.description}</p><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" onClick={() => moderate.mutate({ storeId: store.id, status: "approved" })} disabled={moderate.isPending} className="bg-emerald-300 text-slate-950 hover:bg-emerald-200"><CheckCircle2 className="ml-2 h-4 w-4" />اعتماد</Button><Button size="sm" variant="outline" onClick={() => moderate.mutate({ storeId: store.id, status: "rejected" })} disabled={moderate.isPending} className="border-rose-300/25 text-rose-100 hover:bg-rose-300/10 hover:text-white"><XCircle className="ml-2 h-4 w-4" />رفض</Button></div></article>) : <div className="rounded-2xl border border-dashed border-white/10 p-8 text-center"><Store className="mx-auto h-7 w-7 text-slate-600" /><h3 className="mt-3 font-bold text-white">لا توجد طلبات متجر معلقة</h3><p className="mt-2 text-sm text-slate-500">يبقى السوق فارغًا إلى أن يقدّم مستخدم متجرًا حقيقيًا للمراجعة.</p></div>}</div></section></section></DashboardLayout>;
}
