import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { siteNotificationCategories, type SiteNotificationCategory } from "@shared/siteNotificationPolicy";
import { BellRing, Check, CheckCheck, CircleAlert, ExternalLink, Inbox, Settings2, ShieldCheck } from "lucide-react";
import React from "react";
import { toast } from "sonner";

export default function NotificationCenter() {
  const { direction, t } = useLanguage();
  const utils = trpc.useUtils();
  const notifications = trpc.notifications.list.useQuery();
  const preferences = trpc.notifications.preferences.useQuery();
  const markRead = trpc.notifications.markRead.useMutation({ onSuccess: async () => { await Promise.all([utils.notifications.list.invalidate(), utils.notifications.unreadCount.invalidate()]); }, onError: error => toast.error(error.message) });
  const markAllRead = trpc.notifications.markAllRead.useMutation({ onSuccess: async () => { await Promise.all([utils.notifications.list.invalidate(), utils.notifications.unreadCount.invalidate()]); toast.success("تم تعليم الإشعارات الحالية كمقروءة."); }, onError: error => toast.error(error.message) });
  const updatePreferences = trpc.notifications.updatePreferences.useMutation({ onSuccess: async () => { await utils.notifications.preferences.invalidate(); toast.success("تم حفظ تفضيلات الإشعارات داخل الموقع."); }, onError: error => toast.error(error.message) });
  const data = preferences.data;
  const categoryCopy: Record<SiteNotificationCategory, string> = { workspace: t("notificationCategoryWorkspace"), community: t("notificationCategoryCommunity"), review: t("notificationCategoryReview"), system: t("notificationCategorySystem") };
  const preferenceKeys = [
    { key: "workspaceEnabled" as const, category: "workspace" as const, label: t("notificationWorkspace") },
    { key: "communityEnabled" as const, category: "community" as const, label: t("notificationCommunity") },
    { key: "reviewEnabled" as const, category: "review" as const, label: t("notificationReview") },
    { key: "systemEnabled" as const, category: "system" as const, label: t("notificationSystem") },
  ];

  function updatePreference(key: keyof Pick<NonNullable<typeof data>, "inAppEnabled" | "workspaceEnabled" | "communityEnabled" | "reviewEnabled" | "systemEnabled">, value: boolean) {
    if (!data) return;
    updatePreferences.mutate({ inAppEnabled: data.inAppEnabled, workspaceEnabled: data.workspaceEnabled, communityEnabled: data.communityEnabled, reviewEnabled: data.reviewEnabled, systemEnabled: data.systemEnabled, [key]: value });
  }

  return <DashboardLayout><section dir={direction} className="space-y-6"><header className="relative overflow-hidden rounded-[2rem] border border-cyan-300/15 bg-gradient-to-l from-cyan-400/15 via-slate-950 to-violet-400/10 p-6 sm:p-8"><div className="absolute -left-10 -top-10 h-36 w-36 rounded-full bg-cyan-300/10 blur-3xl" /><Badge className="relative border border-cyan-300/20 bg-cyan-300/10 text-cyan-100"><BellRing className="ml-1 h-3.5 w-3.5" />{t("notificationInSiteOnly")}</Badge><h1 className="relative mt-4 text-2xl font-bold text-white sm:text-3xl">{t("notificationTitle")}</h1><p className="relative mt-2 max-w-3xl leading-8 text-slate-300">{t("notificationIntro")}</p></header>
    <section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="rounded-3xl border border-white/8 bg-slate-950/65 p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold text-white">{t("notificationRecent")}</h2><p className="mt-1 text-sm text-slate-500">{t("notificationRecentCopy")}</p></div><Button type="button" size="sm" variant="outline" onClick={() => markAllRead.mutate()} disabled={markAllRead.isPending || !notifications.data?.some(item => !item.readAt)} className="border-white/15 text-slate-300 hover:bg-white/10 hover:text-white"><CheckCheck className="ml-1 h-4 w-4" />{t("notificationMarkAll")}</Button></div>{notifications.isLoading ? <p className="mt-6 rounded-2xl border border-white/8 p-5 text-sm text-slate-500">{t("notificationLoading")}</p> : notifications.data?.length ? <div className="mt-6 space-y-3">{notifications.data.map(notification => <article key={notification.id} className={`rounded-2xl border p-4 ${notification.readAt ? "border-white/8 bg-white/[0.02]" : "border-cyan-300/20 bg-cyan-300/[0.055]"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><Badge className="border border-white/10 bg-slate-950/55 text-slate-300">{categoryCopy[notification.category]}</Badge><h3 className="mt-3 font-bold text-white">{notification.title}</h3><p className="mt-2 text-sm leading-7 text-slate-400">{notification.body}</p><p className="mt-3 text-xs text-slate-500">{new Date(notification.createdAt).toLocaleString(direction === "rtl" ? "ar" : "en")}</p></div>{notification.readAt ? <span className="inline-flex items-center gap-1 text-xs text-slate-500"><Check className="h-3.5 w-3.5" />{t("notificationRead")}</span> : <Button type="button" size="sm" variant="outline" onClick={() => markRead.mutate({ notificationId: notification.id })} disabled={markRead.isPending} className="border-cyan-300/20 text-cyan-100 hover:bg-cyan-300/10 hover:text-cyan-50">{t("notificationMarkRead")}</Button>}</div>{notification.link ? <a href={`#${notification.link}`} onClick={() => { if (!notification.readAt) markRead.mutate({ notificationId: notification.id }); }} className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-cyan-200 hover:text-cyan-100">{t("notificationOpenLinked")} <ExternalLink className="h-4 w-4" /></a> : null}</article>)}</div> : <div className="mt-6 rounded-3xl border border-dashed border-white/10 p-8 text-center"><Inbox className="mx-auto h-8 w-8 text-slate-600" /><h3 className="mt-3 font-bold text-white">{t("notificationEmptyTitle")}</h3><p className="mt-2 text-sm leading-7 text-slate-500">{t("notificationEmptyCopy")}</p></div>}</div>
      <aside className="space-y-4"><section className="rounded-3xl border border-white/8 bg-slate-950/65 p-5"><div className="flex gap-3"><Settings2 className="mt-0.5 h-5 w-5 shrink-0 text-cyan-300" /><div><h2 className="font-bold text-white">{t("notificationPreferences")}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{t("notificationPreferencesCopy")}</p></div></div><div className="mt-5 space-y-4"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold text-slate-200">{t("notificationInApp")}</p><p className="mt-1 text-xs leading-5 text-slate-500">{t("notificationInAppCopy")}</p></div><Switch checked={data?.inAppEnabled ?? true} disabled={!data || updatePreferences.isPending} onCheckedChange={value => updatePreference("inAppEnabled", value)} aria-label={t("notificationInApp")} /></div>{preferenceKeys.map(item => <div key={item.key} className="flex items-center justify-between gap-3 border-t border-white/8 pt-4"><div><p className="text-sm font-semibold text-slate-200">{item.label}</p><p className="mt-1 text-xs text-slate-500">{categoryCopy[item.category]}</p></div><Switch checked={data?.[item.key] ?? true} disabled={!data || !data.inAppEnabled || updatePreferences.isPending} onCheckedChange={value => updatePreference(item.key, value)} aria-label={item.label} /></div>)}</div></section><section className="rounded-3xl border border-amber-300/15 bg-amber-300/[0.045] p-5"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-amber-300" /><div><h2 className="font-bold text-amber-100">{t("notificationBoundary")}</h2><p className="mt-2 text-sm leading-7 text-amber-100/75">{t("notificationBoundaryCopy")}</p></div></div></section></aside></section><p className="flex gap-2 rounded-2xl border border-white/8 bg-white/[0.025] p-4 text-sm leading-7 text-slate-400"><CircleAlert className="mt-0.5 h-5 w-5 shrink-0 text-cyan-300" />{t("notificationNoFabricated")}</p></section></DashboardLayout>;
}
