import { describe, expect, it, vi } from "vitest";
import type { TrpcContext } from "./_core/context";
const mocks = vi.hoisted(() => ({ saveMemberProfile: vi.fn(), requestCommunityMembership: vi.fn(), createCommunityPost: vi.fn(), reportCommunityTarget: vi.fn(), moderateCommunityItem: vi.fn(), getMyMemberProfile: vi.fn(), searchDiscoverableMembers: vi.fn(), listApprovedCommunities: vi.fn(), listPublicCommunityFeed: vi.fn(), createCommunityRequest: vi.fn(), listMyCommunityMemberships: vi.fn(), listCommunityPosts: vi.fn(), listCommunityReviewQueue: vi.fn() }));
vi.mock("./communities", () => mocks);
import { ENV } from "./_core/env";
import { appRouter } from "./routers";
function context(openId: string | null, id = 44): TrpcContext { return { user: openId ? { id, openId, email: null, name: "Visitor", loginMethod: "manus", role: "user", createdAt: new Date(), updatedAt: new Date(), lastSignedIn: new Date() } : null, req: { protocol: "https", headers: {} } as TrpcContext["req"], res: { clearCookie: () => undefined } as TrpcContext["res"] }; }
describe("community hub router", () => {
  it("binds a profile, post, membership and report to the authenticated visitor", async () => { mocks.saveMemberProfile.mockResolvedValue({ id: 1 }); mocks.requestCommunityMembership.mockResolvedValue({ id: 2 }); mocks.createCommunityPost.mockResolvedValue({ id: 3 }); mocks.reportCommunityTarget.mockResolvedValue({ id: 4 }); const caller = appRouter.createCaller(context("visitor", 44)); await caller.communityHub.saveProfile({ alias: "مطور آمن", discoveryEnabled: true }); await caller.communityHub.requestMembership({ communityId: 9 }); await caller.communityHub.createPost({ communityId: 9, title: "فكرة جلسة", content: "هذا منشور تجريبي صالح للتحقق من هوية العضو." }); await caller.communityHub.report({ targetType: "community", targetId: 9, reason: "سبب بلاغ منظم وواضح" }); expect(mocks.saveMemberProfile).toHaveBeenCalledWith({ userId: 44, alias: "مطور آمن", discoveryEnabled: true }); expect(mocks.requestCommunityMembership).toHaveBeenCalledWith({ userId: 44, communityId: 9 }); expect(mocks.createCommunityPost).toHaveBeenCalledWith(expect.objectContaining({ userId: 44, communityId: 9 })); expect(mocks.reportCommunityTarget).toHaveBeenCalledWith(expect.objectContaining({ reporterId: 44, targetId: 9 })); });
  it("requires authentication for discovery and owner identity for review", async () => { await expect(appRouter.createCaller(context(null)).communityHub.memberSearch({ query: "ويب" })).rejects.toThrow(); await expect(appRouter.createCaller(context("visitor", 44)).communityHub.reviewQueue()).rejects.toThrow("مخصصة للمالك فقط"); mocks.moderateCommunityItem.mockResolvedValue({ id: 5, status: "approved" }); await appRouter.createCaller(context(ENV.ownerOpenId, 2)).communityHub.moderate({ target: "post", id: 5, status: "approved" }); expect(mocks.moderateCommunityItem).toHaveBeenCalledWith({ ownerId: 2, target: "post", id: 5, status: "approved" }); });
  it("allows anonymous readers to receive only a bounded curated public feed contract", async () => { const page = { items: [{ id: 7, title: "نقاش معتمد", content: "نص معتمد", communityId: 4, communityName: "نادي الويب" }], nextCursor: null }; mocks.listPublicCommunityFeed.mockResolvedValue(page); const feed = await appRouter.createCaller(context(null)).communityHub.publicFeed({ limit: 6 }); expect(mocks.listPublicCommunityFeed).toHaveBeenCalledWith({ limit: 6 }); expect(feed).toEqual(page); });
});
