import { and, desc, eq, like, or } from "drizzle-orm";
import { communities, communityMemberships, communityPosts, communityReports, memberProfiles } from "../drizzle/schema";
import { validateCommunityInput, validateCommunityPost, validateCommunityReport, validateProfileInput } from "../shared/communityPolicy";
import { getDb } from "./db";

export function canViewCommunityPost(status: "pending" | "approved" | "rejected" | "archived", authorId: number, viewerId: number) { return status === "approved" || authorId === viewerId; }

export async function getMyMemberProfile(userId: number) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const [profile] = await db.select().from(memberProfiles).where(eq(memberProfiles.userId, userId)).limit(1); return profile ?? null; }
export async function saveMemberProfile(input: { userId: number; alias: string; bio?: string; skills?: string; discoveryEnabled: boolean }) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const validated = validateProfileInput(input); const existing = await getMyMemberProfile(input.userId); if (existing) { await db.update(memberProfiles).set({ ...validated, updatedAt: new Date() }).where(eq(memberProfiles.id, existing.id)); return { ...existing, ...validated }; } const [created] = await db.insert(memberProfiles).values({ userId: input.userId, ...validated }).$returningId(); const [profile] = await db.select().from(memberProfiles).where(eq(memberProfiles.id, created.id)).limit(1); if (!profile) throw new Error("تعذر حفظ الملف"); return profile; }
export async function searchDiscoverableMembers(query: string) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const value = query.trim(); if (value.length < 2) return []; return db.select({ id: memberProfiles.id, alias: memberProfiles.alias, bio: memberProfiles.bio, skills: memberProfiles.skills }).from(memberProfiles).where(and(eq(memberProfiles.discoveryEnabled, true), eq(memberProfiles.status, "active"), or(like(memberProfiles.alias, `%${value}%`), like(memberProfiles.skills, `%${value}%`)))).limit(30); }
export async function listApprovedCommunities() { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); return db.select().from(communities).where(eq(communities.status, "approved")).orderBy(desc(communities.updatedAt)).limit(100); }
export async function createCommunityRequest(input: { userId: number; name: string; description: string }) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const validated = validateCommunityInput(input); const [created] = await db.insert(communities).values({ ownerId: input.userId, ...validated, status: "pending" }).$returningId(); await db.insert(communityMemberships).values({ communityId: created.id, userId: input.userId, role: "owner", status: "approved" }); return { id: created.id, status: "pending" as const }; }
export async function listMyCommunityMemberships(userId: number) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); return db.select().from(communityMemberships).where(eq(communityMemberships.userId, userId)).orderBy(desc(communityMemberships.updatedAt)); }
export async function requestCommunityMembership(input: { userId: number; communityId: number }) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const [community] = await db.select().from(communities).where(and(eq(communities.id, input.communityId), eq(communities.status, "approved"))).limit(1); if (!community) throw new Error("هذا المجتمع غير متاح للانضمام"); const [existing] = await db.select().from(communityMemberships).where(and(eq(communityMemberships.communityId, input.communityId), eq(communityMemberships.userId, input.userId))).limit(1); if (existing) return existing; const [created] = await db.insert(communityMemberships).values({ communityId: input.communityId, userId: input.userId, status: "pending" }).$returningId(); const [membership] = await db.select().from(communityMemberships).where(eq(communityMemberships.id, created.id)).limit(1); if (!membership) throw new Error("تعذر حفظ طلب الانضمام"); return membership; }
export async function listCommunityPosts(input: { userId: number; communityId: number }) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const [community] = await db.select().from(communities).where(and(eq(communities.id, input.communityId), eq(communities.status, "approved"))).limit(1); if (!community) throw new Error("المجتمع غير متاح"); const [membership] = await db.select().from(communityMemberships).where(and(eq(communityMemberships.communityId, input.communityId), eq(communityMemberships.userId, input.userId))).limit(1); const posts = await db.select().from(communityPosts).where(and(eq(communityPosts.communityId, input.communityId), or(eq(communityPosts.status, "approved"), eq(communityPosts.authorId, input.userId)))).orderBy(desc(communityPosts.createdAt)).limit(100); return { community, membership: membership ?? null, posts: posts.filter(post => canViewCommunityPost(post.status, post.authorId, input.userId)) }; }
export async function createCommunityPost(input: { userId: number; communityId: number; title: string; content: string }) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const [membership] = await db.select().from(communityMemberships).where(and(eq(communityMemberships.communityId, input.communityId), eq(communityMemberships.userId, input.userId), eq(communityMemberships.status, "approved"))).limit(1); if (!membership) throw new Error("تحتاج عضوية معتمدة قبل النشر"); const validated = validateCommunityPost(input); const [created] = await db.insert(communityPosts).values({ communityId: input.communityId, authorId: input.userId, ...validated, status: "pending" }).$returningId(); return { id: created.id, status: "pending" as const }; }
export async function reportCommunityTarget(input: { reporterId: number; targetType: "community" | "post" | "member"; targetId: number; reason: string }) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const reason = validateCommunityReport(input.reason); const [created] = await db.insert(communityReports).values({ reporterId: input.reporterId, targetType: input.targetType, targetId: input.targetId, reason, status: "open" }).$returningId(); return { id: created.id, status: "open" as const }; }
export async function listCommunityReviewQueue() { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const [pendingCommunities, pendingMemberships, pendingPosts, reports] = await Promise.all([db.select().from(communities).where(eq(communities.status, "pending")).orderBy(desc(communities.createdAt)).limit(100), db.select().from(communityMemberships).where(eq(communityMemberships.status, "pending")).orderBy(desc(communityMemberships.createdAt)).limit(100), db.select().from(communityPosts).where(eq(communityPosts.status, "pending")).orderBy(desc(communityPosts.createdAt)).limit(100), db.select().from(communityReports).where(eq(communityReports.status, "open")).orderBy(desc(communityReports.createdAt)).limit(100)]); return { communities: pendingCommunities, memberships: pendingMemberships, posts: pendingPosts, reports }; }
export async function moderateCommunityItem(input: { ownerId: number; target: "community" | "membership" | "post" | "report"; id: number; status: "approved" | "rejected" | "archived" | "blocked" | "resolved" | "dismissed"; note?: string }) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const note = input.note?.trim() || null; if (input.target === "community" && ["approved", "rejected", "archived"].includes(input.status)) { await db.update(communities).set({ status: input.status as "approved" | "rejected" | "archived", moderatorId: input.ownerId, moderationNote: note, updatedAt: new Date() }).where(eq(communities.id, input.id)); } else if (input.target === "membership" && ["approved", "rejected", "blocked"].includes(input.status)) { await db.update(communityMemberships).set({ status: input.status as "approved" | "rejected" | "blocked", reviewerId: input.ownerId, moderationNote: note, updatedAt: new Date() }).where(eq(communityMemberships.id, input.id)); } else if (input.target === "post" && ["approved", "rejected", "archived"].includes(input.status)) { await db.update(communityPosts).set({ status: input.status as "approved" | "rejected" | "archived", reviewerId: input.ownerId, moderationNote: note, updatedAt: new Date() }).where(eq(communityPosts.id, input.id)); } else if (input.target === "report" && ["resolved", "dismissed"].includes(input.status)) { await db.update(communityReports).set({ status: input.status as "resolved" | "dismissed", handlerId: input.ownerId, resolutionNote: note, updatedAt: new Date() }).where(eq(communityReports.id, input.id)); } else throw new Error("قرار المراجعة غير صالح لهذا العنصر"); return { id: input.id, status: input.status }; }
