import { describe, expect, it, vi } from "vitest";
import type { TrpcContext } from "./_core/context";
const mocks = vi.hoisted(() => ({ save: vi.fn(), get: vi.fn(), list: vi.fn(), updateDraft: vi.fn(), attach: vi.fn(), createHeartbeatJob: vi.fn(), updateHeartbeatJob: vi.fn() }));
vi.mock("./periodicDevelopment", () => ({ savePeriodicDevelopmentJob: mocks.save, getPeriodicDevelopmentJob: mocks.get, listPeriodicDevelopmentDrafts: mocks.list, updatePeriodicDevelopmentDraft: mocks.updateDraft, attachPeriodicDevelopmentSchedule: mocks.attach, getPeriodicDevelopmentCron: () => "0 0 */6 * * *" }));
vi.mock("./_core/heartbeat", () => ({ createHeartbeatJob: mocks.createHeartbeatJob, updateHeartbeatJob: mocks.updateHeartbeatJob }));
import { ENV } from "./_core/env";
import { appRouter } from "./routers";
function context(openId: string, id: number): TrpcContext { return { user: { id, openId, email: null, name: "User", loginMethod: "manus", role: "user", createdAt: new Date(), updatedAt: new Date(), lastSignedIn: new Date() }, req: { headers: { cookie: "" } } as TrpcContext["req"], res: { clearCookie: () => undefined } as TrpcContext["res"] }; }
describe("periodic development router", () => { it("limits configuration to the owner and stores a schedule identity without changing platform code", async () => { await expect(appRouter.createCaller(context("visitor", 9)).periodicDevelopment.status()).rejects.toThrow("مخصصة للمالك فقط"); mocks.save.mockResolvedValue({ id: 5, ownerId: 2, cadence: "every-6-hours", scheduleCronTaskUid: null }); mocks.createHeartbeatJob.mockResolvedValue({ taskUid: "cron_job_5" }); mocks.attach.mockResolvedValue({ id: 5, scheduleCronTaskUid: "cron_job_5" }); const result = await appRouter.createCaller(context(ENV.ownerOpenId, 2)).periodicDevelopment.configure({ cadence: "every-6-hours" }); expect(mocks.createHeartbeatJob).toHaveBeenCalledWith(expect.objectContaining({ path: "/api/scheduled/periodic-development", cron: "0 0 */6 * * *" }), ""); expect(mocks.attach).toHaveBeenCalledWith({ ownerId: 2, taskUid: "cron_job_5" }); expect(result).toMatchObject({ scheduleCronTaskUid: "cron_job_5" }); }); });
