import { and, desc, eq } from "drizzle-orm";
import { communities, communityPosts, periodicDevelopmentDrafts, periodicDevelopmentJobs, projects, sourceFiles, visitorSubmissions } from "../drizzle/schema";
import { invokeLLM } from "./_core/llm";
import { getDb } from "./db";
import { parsePeriodicDevelopmentDraft, periodicDevelopmentOutputSchema, periodicDevelopmentSafetyInstruction, periodicDraftKinds, type PeriodicDraftKind } from "./periodicDevelopmentPolicy";

export function getPeriodicDevelopmentCron(cadence: "hourly" | "every-6-hours") { return cadence === "hourly" ? "0 0 * * * *" : "0 0 */6 * * *"; }
export async function getPeriodicDevelopmentJob(ownerId: number) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const [job] = await db.select().from(periodicDevelopmentJobs).where(eq(periodicDevelopmentJobs.ownerId, ownerId)).limit(1); return job ?? null; }
export async function savePeriodicDevelopmentJob(input: { ownerId: number; cadence: "hourly" | "every-6-hours"; status?: "active" | "paused" }) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const current = await getPeriodicDevelopmentJob(input.ownerId); if (current) { await db.update(periodicDevelopmentJobs).set({ cadence: input.cadence, status: input.status ?? "active", updatedAt: new Date() }).where(eq(periodicDevelopmentJobs.id, current.id)); return { ...current, cadence: input.cadence, status: input.status ?? "active" }; } const [created] = await db.insert(periodicDevelopmentJobs).values({ ownerId: input.ownerId, cadence: input.cadence, status: input.status ?? "active" }).$returningId(); const [job] = await db.select().from(periodicDevelopmentJobs).where(eq(periodicDevelopmentJobs.id, created.id)).limit(1); if (!job) throw new Error("تعذر إعداد مهمة التطوير الدورية"); return job; }
export async function attachPeriodicDevelopmentSchedule(input: { ownerId: number; taskUid: string }) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const job = await getPeriodicDevelopmentJob(input.ownerId); if (!job) throw new Error("أعد إعداد المهمة الدورية أولًا"); await db.update(periodicDevelopmentJobs).set({ scheduleCronTaskUid: input.taskUid, status: "active", lastError: null, updatedAt: new Date() }).where(eq(periodicDevelopmentJobs.id, job.id)); return { ...job, scheduleCronTaskUid: input.taskUid, status: "active" as const, lastError: null }; }
export async function listPeriodicDevelopmentDrafts(ownerId: number) { const db = await getDb(); if (!db) return []; return db.select().from(periodicDevelopmentDrafts).where(eq(periodicDevelopmentDrafts.ownerId, ownerId)).orderBy(desc(periodicDevelopmentDrafts.createdAt)).limit(30); }
export async function updatePeriodicDevelopmentDraft(input: { ownerId: number; id: number; status: "acknowledged" | "dismissed" }) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); await db.update(periodicDevelopmentDrafts).set({ status: input.status, updatedAt: new Date() }).where(and(eq(periodicDevelopmentDrafts.id, input.id), eq(periodicDevelopmentDrafts.ownerId, input.ownerId))); return { id: input.id, status: input.status }; }
async function createBoundedSnapshot(ownerId: number) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const [ownedProjects, privateFiles, pendingVisitorSubmissions, pendingCommunities, pendingPosts, priorDrafts] = await Promise.all([db.select({ id: projects.id }).from(projects).where(eq(projects.ownerId, ownerId)), db.select({ id: sourceFiles.id }).from(sourceFiles).where(eq(sourceFiles.ownerId, ownerId)), db.select({ id: visitorSubmissions.id }).from(visitorSubmissions).where(eq(visitorSubmissions.status, "pending")), db.select({ id: communities.id }).from(communities).where(eq(communities.status, "pending")), db.select({ id: communityPosts.id }).from(communityPosts).where(eq(communityPosts.status, "pending")), db.select({ id: periodicDevelopmentDrafts.id }).from(periodicDevelopmentDrafts).where(eq(periodicDevelopmentDrafts.ownerId, ownerId))]); return { projects: ownedProjects.length, privateSourceFiles: privateFiles.length, pendingVisitorSubmissions: pendingVisitorSubmissions.length, pendingCommunities: pendingCommunities.length, pendingCommunityPosts: pendingPosts.length, priorDrafts: priorDrafts.length }; }
export async function runPeriodicDevelopmentDraft(taskUid: string) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا"); const [job] = await db.select().from(periodicDevelopmentJobs).where(and(eq(periodicDevelopmentJobs.scheduleCronTaskUid, taskUid), eq(periodicDevelopmentJobs.status, "active"))).limit(1); if (!job) return { ok: true, skipped: "orphan-or-paused" as const }; try { const snapshot = await createBoundedSnapshot(job.ownerId); const kind = periodicDraftKinds[snapshot.priorDrafts % periodicDraftKinds.length] as PeriodicDraftKind; const response = await invokeLLM({ model: "gpt-5-mini", maxCompletionTokens: 700, reasoning: { effort: "minimal" }, response_format: periodicDevelopmentOutputSchema, messages: [{ role: "system", content: periodicDevelopmentSafetyInstruction }, { role: "user", content: `نوع المراجعة المطلوب: ${kind}.\nملخص مؤشرات المنصة (لا يحتوي شفرة أو أسرارًا أو بيانات شخصية):\n${JSON.stringify(snapshot)}\nأنتج مسودة واحدة واقعية من 2-4 تغييرات مقترحة فقط.` }] }); const content = response.choices[0]?.message.content; if (typeof content !== "string" || !content.trim()) throw new Error("لم يُرجع النموذج مسودة صالحة"); const draft = parsePeriodicDevelopmentDraft(content); await db.insert(periodicDevelopmentDrafts).values({ jobId: job.id, ownerId: job.ownerId, kind: draft.kind, status: "proposed", title: draft.title.slice(0, 180), summary: draft.summary, proposedChanges: JSON.stringify(draft.proposedChanges), codeDraft: JSON.stringify(draft.codeDraft), testPlan: JSON.stringify(draft.testPlan), risks: JSON.stringify(draft.risks), approvalsRequired: JSON.stringify(draft.approvalsRequired) }); await db.update(periodicDevelopmentJobs).set({ lastRunAt: new Date(), lastError: null, status: "active", updatedAt: new Date() }).where(eq(periodicDevelopmentJobs.id, job.id)); return { ok: true, draftKind: draft.kind }; } catch (error) { const message = error instanceof Error ? error.message.slice(0, 500) : "تعذر إنتاج مسودة التطوير"; await db.update(periodicDevelopmentJobs).set({ lastError: message, status: "error", updatedAt: new Date() }).where(eq(periodicDevelopmentJobs.id, job.id)); throw error; } }
