export const communityRules = { profileAliasMin: 3, profileAliasMax: 48, profileBioMax: 500, profileSkillsMax: 240, communityNameMin: 3, communityNameMax: 100, communityDescriptionMin: 12, communityDescriptionMax: 3000, postTitleMin: 3, postTitleMax: 180, postContentMin: 12, postContentMax: 6000, reportReasonMin: 6, reportReasonMax: 500 } as const;
const unsafeProfileFields = /(?:@|https?:\/\/|www\.|\+?\d[\d\s()-]{6,})/i;
export function normalizeCommunityText(value: string) { return value.trim().replace(/\s+/g, " "); }
export function validatePublicAlias(value: string) { const alias = normalizeCommunityText(value); if (alias.length < communityRules.profileAliasMin || alias.length > communityRules.profileAliasMax) throw new Error("الاسم العام يجب أن يكون بين 3 و48 حرفًا"); if (unsafeProfileFields.test(alias)) throw new Error("لا تضع بريدًا أو رابطًا أو رقم هاتف في الاسم العام"); return alias; }
export function validateProfileInput(input: { alias: string; bio?: string; skills?: string; discoveryEnabled: boolean }) { const alias = validatePublicAlias(input.alias); const bio = normalizeCommunityText(input.bio ?? ""); const skills = normalizeCommunityText(input.skills ?? ""); if (bio.length > communityRules.profileBioMax) throw new Error("النبذة أطول من الحد المسموح"); if (skills.length > communityRules.profileSkillsMax) throw new Error("المهارات أطول من الحد المسموح"); if (unsafeProfileFields.test(bio) || unsafeProfileFields.test(skills)) throw new Error("لا تضع بريدًا أو رابطًا أو رقم هاتف في الملف العام"); return { alias, bio: bio || null, skills: skills || null, discoveryEnabled: input.discoveryEnabled }; }
export function validateCommunityInput(input: { name: string; description: string }) { const name = normalizeCommunityText(input.name); const description = input.description.trim(); if (name.length < communityRules.communityNameMin || name.length > communityRules.communityNameMax) throw new Error("اسم المجتمع يجب أن يكون بين 3 و100 حرف"); if (description.length < communityRules.communityDescriptionMin || description.length > communityRules.communityDescriptionMax) throw new Error("وصف المجتمع يجب أن يكون بين 12 و3000 حرف"); if (unsafeProfileFields.test(name) || unsafeProfileFields.test(description)) throw new Error("لا تضع بيانات اتصال أو روابط في طلب المجتمع"); return { name, description }; }
export function validateCommunityPost(input: { title: string; content: string }) { const title = normalizeCommunityText(input.title); const content = input.content.trim(); if (title.length < communityRules.postTitleMin || title.length > communityRules.postTitleMax) throw new Error("عنوان المنشور يجب أن يكون بين 3 و180 حرفًا"); if (content.length < communityRules.postContentMin || content.length > communityRules.postContentMax) throw new Error("محتوى المنشور يجب أن يكون بين 12 و6000 حرف"); return { title, content }; }
export function validateCommunityReport(reason: string) { const normalized = reason.trim(); if (normalized.length < communityRules.reportReasonMin || normalized.length > communityRules.reportReasonMax) throw new Error("سبب البلاغ يجب أن يكون بين 6 و500 حرف"); return normalized; }
export const communityPolicyCopy = "الملفات العامة اختيارية ومخفية افتراضيًا. طلبات المجتمعات والعضوية والمنشورات تمر بالمراجعة، ويمكن الإبلاغ عن المحتوى أو حجب العضوية عند الحاجة.";
