import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { MessageSquareHeart, UsersRound } from "lucide-react";
import React from "react";
import { Link } from "wouter";

export default function CommunityFeed() {
  const feed = trpc.communityHub.publicFeed.useQuery();
  return <section className="container relative z-10 py-12 lg:py-20" aria-label="تغذية المجتمعات"><div className="rounded-[2rem] border border-violet-300/15 bg-gradient-to-l from-violet-300/[0.07] to-slate-950/20 p-6 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><Badge className="border border-violet-300/20 bg-violet-300/10 text-violet-100"><UsersRound className="ml-1 h-3.5 w-3.5" />مجتمعات DevForge</Badge><h2 className="mt-4 text-2xl font-bold text-white sm:text-3xl">نقاشات معتمدة من المجتمع</h2><p className="mt-2 max-w-2xl leading-7 text-slate-400">تظهر هنا المنشورات التي اعتمدها المالك فقط. لا نعرض ملفات شخصية خاصة أو طلبات أو محتوى معلّق.</p></div><Link href="/community" className="rounded-xl border border-cyan-300/25 bg-cyan-300/8 px-4 py-2 text-sm font-bold text-cyan-100 transition hover:bg-cyan-300/15">استكشف المجتمعات</Link></div><div className="mt-6 grid gap-4 md:grid-cols-2">{feed.isLoading ? <p className="text-sm text-slate-500">يجري تحميل النقاشات المعتمدة…</p> : feed.data?.length ? feed.data.map(item => <article key={item.id} className="rounded-2xl border border-white/8 bg-slate-950/60 p-5"><p className="text-xs font-bold text-violet-200">{item.communityName}</p><h3 className="mt-2 font-bold text-white">{item.title}</h3><p className="mt-3 line-clamp-4 whitespace-pre-wrap text-sm leading-7 text-slate-400">{item.content}</p><p className="mt-4 text-[11px] text-slate-600">{new Date(item.createdAt).toLocaleDateString("ar")}</p></article>) : <div className="rounded-2xl border border-dashed border-white/10 p-6 text-center md:col-span-2"><MessageSquareHeart className="mx-auto h-6 w-6 text-violet-300" /><p className="mt-3 font-semibold text-slate-300">لا توجد منشورات معتمدة بعد.</p><p className="mt-1 text-sm leading-6 text-slate-500">يمكن للأعضاء طلب الانضمام ثم إرسال منشورات للمراجعة.</p></div>}</div></div></section>;
}
